// apps/react-demo/src/App.tsx
import React, { useCallback, useRef, useState } from 'react'

import { MpegtsPlayer, type MpegtsPlayerRef, type PlayerStatus } from 'mpegts-react'

const DEFAULT_URL = 'ws://192.168.100.94:15354/live/chn1.flv'

const STATUS_COLORS: Record<PlayerStatus, string> = {
  connecting: 'text-yellow-500',
  destroying: 'text-gray-400',
  error: 'text-red-500',
  nosignal: 'text-gray-400',
  playing: 'text-green-500',
  stopped: 'text-gray-400',
}

export default function App() {
  const playerRef = useRef<MpegtsPlayerRef>(null)
  const [url, setUrl] = useState(DEFAULT_URL)
  const [inputUrl, setInputUrl] = useState(DEFAULT_URL)
  const [muted, setMuted] = useState(true)
  const [status, setStatus] = useState<PlayerStatus>('nosignal')

  const applyUrl = useCallback(() => {
    const trimmed = inputUrl.trim()
    setUrl(trimmed)
    setInputUrl(trimmed)
  }, [inputUrl])

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') applyUrl()
    },
    [applyUrl],
  )

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6">
      <div className="mx-auto max-w-5xl flex flex-col gap-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <svg
              className="size-6 text-blue-500"
              fill="none"
              stroke="currentColor"
              strokeWidth={1.5}
              viewBox="0 0 24 24"
            >
              <path
                d="m15.75 10.5 4.72-4.72a.75.75 0 0 1 1.28.53v11.38a.75.75 0 0 1-1.28.53l-4.72-4.72M4.5 18.75h9a2.25 2.25 0 0 0 2.25-2.25v-9a2.25 2.25 0 0 0-2.25-2.25h-9A2.25 2.25 0 0 0 2.25 7.5v9a2.25 2.25 0 0 0 2.25 2.25Z"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
            <h2 className="m-0 text-lg font-semibold">mpegts-react Demo</h2>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-400">Status:</span>
            <span className={`text-sm font-medium ${STATUS_COLORS[status]}`}>
              {status}
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6 xl:grid-cols-3">
          <div className="xl:col-span-2">
            <div className="aspect-video w-full rounded-lg border border-gray-700 bg-black shadow-sm">
              <MpegtsPlayer
                ref={playerRef}
                url={url}
                muted={muted}
                onStatus={setStatus}
              />
            </div>
          </div>

          <div className="flex flex-col gap-4">
            <div className="rounded-lg border border-gray-700 bg-gray-900 p-4">
              <h3 className="m-0 mb-3 text-sm font-semibold">Stream URL</h3>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={inputUrl}
                  onChange={(e) => setInputUrl(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="ws://host:port/live/stream.flv"
                  className="flex-1 rounded border border-gray-600 bg-gray-800 px-3 py-1.5 text-xs text-white outline-none focus:border-blue-500"
                />
                <button
                  className="rounded bg-blue-600 px-3 py-1.5 text-xs text-white hover:bg-blue-700"
                  onClick={applyUrl}
                >
                  Apply
                </button>
              </div>
              <div className="mt-3 flex flex-wrap gap-2">
                <button
                  className={`rounded border px-2 py-1 text-xs transition-colors ${
                    url === DEFAULT_URL
                      ? 'border-blue-500 text-blue-500'
                      : 'border-gray-700 hover:border-blue-500 hover:text-blue-500'
                  }`}
                  onClick={() => {
                    setInputUrl(DEFAULT_URL)
                    setUrl(DEFAULT_URL)
                  }}
                >
                  Channel 1
                </button>
              </div>
            </div>

            <div className="rounded-lg border border-gray-700 bg-gray-900 p-4">
              <h3 className="m-0 mb-3 text-sm font-semibold">Playback</h3>
              <div className="flex flex-col gap-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-gray-400">Muted</span>
                  <button
                    className={`rounded border px-3 py-1 text-xs transition-colors ${
                      muted
                        ? 'border-blue-500 bg-blue-500/10 text-blue-500'
                        : 'border-gray-700 hover:border-blue-500'
                    }`}
                    onClick={() => setMuted((v) => !v)}
                  >
                    {muted ? 'ON' : 'OFF'}
                  </button>
                </div>
                <div className="flex gap-2">
                  <button
                    className="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                    onClick={() => playerRef.current?.play()}
                  >
                    Play
                  </button>
                  <button
                    className="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                    onClick={() => playerRef.current?.pause()}
                  >
                    Pause
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// apps/demo/src/App.vue
<script setup lang="ts">
import { computed, ref, shallowReactive } from 'vue';

import { Languages, Monitor } from 'lucide-vue-next';

import { Input, Slider, Switch } from 'antdv-next';

import { MpegtsPlayer } from 'mpegts-vue3';
import type { PlayerStatus } from 'mpegts-vue3';

import { t, toggleLocale, useLocale } from './i18n';

type GridLayout = 1 | 4 | 9;

const lang = useLocale();
const langLabel = computed(() => (lang.value === 'en' ? '中文' : 'EN'));

const DEFAULT_URL = 'ws://192.168.100.94:15354/live/chn1.flv';

const gridLayout = ref<GridLayout>(1);
const muted = ref(true);
const inputUrl = ref(DEFAULT_URL);

const presets = computed(() => [
  { label: `${t('channel')} 1`, url: 'ws://192.168.100.94:15354/live/chn1.flv' },
  { label: `${t('channel')} 2`, url: 'ws://192.168.100.94:15354/live/chn2.flv' },
]);

const gridSlots = computed(() => {
  return Array.from({ length: gridLayout.value }, (_, i) => ({
    id: i,
  }));
});

const playerRefs = ref<Record<number, InstanceType<typeof MpegtsPlayer>>>({});
const playerStatuses = ref<Record<number, PlayerStatus>>({});

const activePlayerStatus = computed<PlayerStatus>(() => {
  if (gridLayout.value === 1) {
    return playerStatuses.value[0] ?? 'nosignal';
  }
  return 'playing';
});

const statusColor = computed(() => {
  const map: Record<PlayerStatus, string> = {
    connecting: 'text-yellow-500',
    destroying: 'text-gray-400',
    error: 'text-red-500',
    nosignal: 'text-gray-400',
    playing: 'text-green-500',
    stopped: 'text-gray-400',
  };
  return map[activePlayerStatus.value];
});

const statusText = computed(() => {
  const key = activePlayerStatus.value as string
  return t(key)
});

const config = shallowReactive({
  enableStashBuffer: false,
  stashInitialSize: 384,
  liveBufferLatencyChasing: true,
  liveBufferLatencyChasingOnPaused: true,
  liveBufferLatencyMaxLatency: 1.5,
  liveBufferLatencyMinRemain: 0.3,
  liveSync: true,
  liveSyncMaxLatency: 1.2,
  liveSyncTargetLatency: 0.5,
  autoCleanupSourceBuffer: true,
  autoCleanupMaxBackwardDuration: 30,
  autoCleanupMinBackwardDuration: 10,
  fixAudioTimestampGap: true,
});

function applyUrl() {
  inputUrl.value = inputUrl.value.trim();
}

function setPreset(url: string) {
  inputUrl.value = url;
}

function onPlayerStatus(index: number, s: PlayerStatus) {
  playerStatuses.value[index] = s;
}

function playAll() {
  for (const r of Object.values(playerRefs.value)) {
    r?.play();
  }
}

function pauseAll() {
  for (const r of Object.values(playerRefs.value)) {
    r?.pause();
  }
}

function setPlayerRef(
  index: number,
  el: InstanceType<typeof MpegtsPlayer> | null,
) {
  if (el) {
    playerRefs.value[index] = el;
  } else {
    delete playerRefs.value[index];
  }
}

const gridColsClass = computed(() => {
  if (gridLayout.value === 9) return 'grid-cols-3';
  if (gridLayout.value === 4) return 'grid-cols-2';
  return 'grid-cols-1';
});
</script>

<template>
  <div class="min-h-screen bg-gray-950 text-white p-6">
    <div class="mx-auto max-w-7xl flex flex-col gap-6">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <Monitor class="size-6 text-blue-500" />
          <h2 class="m-0 text-lg font-semibold">{{ t('title') }}</h2>
        </div>
        <div class="flex items-center gap-4">
          <div class="flex items-center gap-2">
            <span class="text-xs text-gray-400">{{ t('status') }}:</span>
            <span class="text-sm font-medium" :class="statusColor">
              {{ statusText }}
            </span>
          </div>
          <button
            class="flex items-center gap-1 rounded border border-gray-700 px-2 py-1 text-xs transition-colors hover:border-blue-500 hover:text-blue-500"
            @click="toggleLocale"
          >
            <Languages class="size-3.5" />
            {{ langLabel }}
          </button>
        </div>
      </div>

      <div class="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div class="xl:col-span-2">
          <div class="mb-3 flex items-center gap-2">
            <span class="text-xs text-gray-400">{{ t('windows') }}:</span>
            <button
              v-for="layout in [1, 4, 9] as GridLayout[]"
              :key="layout"
              class="rounded border px-2 py-1 text-xs transition-colors"
              :class="
                gridLayout === layout
                  ? 'border-blue-500 bg-blue-500/10 text-blue-500'
                  : 'border-gray-700 hover:border-blue-500 hover:text-blue-500'
              "
              @click="gridLayout = layout"
            >
              {{ layout }} {{ layout === 1 ? t('window') : t('windows') }}
            </button>
            <div class="ml-auto flex gap-2">
              <button
                class="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                @click="playAll"
              >
                {{ t('playAll') }}
              </button>
              <button
                class="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                @click="pauseAll"
              >
                {{ t('pauseAll') }}
              </button>
            </div>
          </div>

          <div
            v-if="gridLayout === 1"
            class="aspect-video w-full rounded-lg border border-gray-700 bg-black shadow-sm"
          >
            <MpegtsPlayer
              :ref="(el: any) => setPlayerRef(0, el)"
              :src="inputUrl"
              :muted="muted"
              @status="(s: PlayerStatus) => onPlayerStatus(0, s)"
            />
          </div>

          <div v-else class="grid w-full gap-2" :class="gridColsClass">
            <div
              v-for="slot in gridSlots"
              :key="slot.id"
              class="aspect-video rounded-lg border border-gray-700 bg-black shadow-sm"
            >
              <MpegtsPlayer
                :ref="(el: any) => setPlayerRef(slot.id, el)"
                :src="inputUrl"
                :muted="muted"
                @status="(s: PlayerStatus) => onPlayerStatus(slot.id, s)"
              />
            </div>
          </div>
        </div>

        <div class="flex flex-col gap-4">
          <div class="rounded-lg border border-gray-700 bg-gray-900 p-4">
            <h3 class="m-0 mb-3 text-sm font-semibold">{{ t('streamUrl') }}</h3>
            <div class="flex gap-2">
              <Input
                v-model:value="inputUrl"
                placeholder="ws://host:port/live/stream.flv"
                class="flex-1"
                size="small"
                @press-enter="applyUrl"
              />
              <button
                class="rounded bg-blue-600 px-3 py-1 text-xs text-white hover:bg-blue-700"
                @click="applyUrl"
              >
                {{ t('apply') }}
              </button>
            </div>
            <div class="mt-3 flex flex-wrap gap-2">
              <button
                v-for="preset in presets"
                :key="preset.label"
                class="rounded border border-gray-700 px-2 py-1 text-xs transition-colors hover:border-blue-500 hover:text-blue-500"
                :class="{
                  'border-blue-500 text-blue-500': inputUrl === preset.url,
                }"
                @click="setPreset(preset.url)"
              >
                {{ preset.label }}
              </button>
            </div>
          </div>

          <div class="rounded-lg border border-gray-700 bg-gray-900 p-4">
            <h3 class="m-0 mb-3 text-sm font-semibold">{{ t('playbackControl') }}</h3>
            <div class="flex flex-col gap-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">{{ t('muted') }}</span>
                <Switch v-model:checked="muted" size="small" />
              </div>
              <div class="flex gap-2">
                <button
                  class="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                  @click="playAll"
                >
                  {{ t('play') }}
                </button>
                <button
                  class="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                  @click="pauseAll"
                >
                  {{ t('pause') }}
                </button>
              </div>
            </div>
          </div>

          <div class="rounded-lg border border-gray-700 bg-gray-900 p-4">
            <h3 class="m-0 mb-3 text-sm font-semibold">{{ t('liveParameters') }}</h3>
            <div class="flex flex-col gap-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('enableStashBuffer') }}
                </span>
                <Switch
                  v-model:checked="config.enableStashBuffer"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('stashInitialSize') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.stashInitialSize }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.stashInitialSize"
                  :min="64"
                  :max="2048"
                  :step="64"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('latencyChasing') }}
                </span>
                <Switch
                  v-model:checked="config.liveBufferLatencyChasing"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('chaseOnPause') }}
                </span>
                <Switch
                  v-model:checked="config.liveBufferLatencyChasingOnPaused"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('maxLatency') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveBufferLatencyMaxLatency }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveBufferLatencyMaxLatency"
                  :min="0.5"
                  :max="10"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('minRemain') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveBufferLatencyMinRemain }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveBufferLatencyMinRemain"
                  :min="0.1"
                  :max="5"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('rateSync') }}
                </span>
                <Switch v-model:checked="config.liveSync" size="small" />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('syncMaxLatency') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveSyncMaxLatency }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveSyncMaxLatency"
                  :min="0.5"
                  :max="10"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('syncTargetLatency') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveSyncTargetLatency }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveSyncTargetLatency"
                  :min="0.1"
                  :max="5"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('autoCleanup') }}
                </span>
                <Switch
                  v-model:checked="config.autoCleanupSourceBuffer"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('cleanupMaxBackward') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.autoCleanupMaxBackwardDuration }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.autoCleanupMaxBackwardDuration"
                  :min="5"
                  :max="300"
                  :step="5"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('cleanupMinBackward') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.autoCleanupMinBackwardDuration }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.autoCleanupMinBackwardDuration"
                  :min="5"
                  :max="120"
                  :step="5"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('fixAudioTimestampGap') }}
                </span>
                <Switch
                  v-model:checked="config.fixAudioTimestampGap"
                  size="small"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
